development:
  facebook:
    report_url: https://www.facebook.com/help/contact/1449082462070065
    tokens:
      - EAAZApSMxNcVcBANrOVV8FeWhZCV47AUO8YeU4meEqWZCZCCGYxcpFvvu7lETLo8ExPYfqBAiyGyHKjLlTCEtQ1JhcVaMca93VLzu9xRleHLvGka96ZCR2BRAEndSzwxnNz8vkDoMyY2J808Bkg3jvNZCOrPoCCkQUZD # temporary

production:
  facebook:
    report_url: https://www.facebook.com/help/contact/1449082462070065
    tokens:
      - EAAZApSMxNcVcBANrOVV8FeWhZCV47AUO8YeU4meEqWZCZCCGYxcpFvvu7lETLo8ExPYfqBAiyGyHKjLlTCEtQ1JhcVaMca93VLzu9xRleHLvGka96ZCR2BRAEndSzwxnNz8vkDoMyY2J808Bkg3jvNZCOrPoCCkQUZD # temporary

demo:
  facebook:
    report_url: https://www.facebook.com/help/contact/1449082462070065
    tokens:
      - EAAZApSMxNcVcBANrOVV8FeWhZCV47AUO8YeU4meEqWZCZCCGYxcpFvvu7lETLo8ExPYfqBAiyGyHKjLlTCEtQ1JhcVaMca93VLzu9xRleHLvGka96ZCR2BRAEndSzwxnNz8vkDoMyY2J808Bkg3jvNZCOrPoCCkQUZD # temporary

test:
  facebook:
    report_url: https://www.facebook.com/help/contact/1449082462070065
    tokens:
      - EAAIUKbXn8xsBAPsYb2xKl4fcrpDnJKQZCrZB2EuLjHyg4GrXrlqnd1xHROqV3DFFbPRuzILTEwtoXLr5fo8PTxvvyN68uPUpbvCwnoIPrdJLmmKkuJXd2dMGekT8THoc2eZBuftIVXaLTN656NYzpxOu9FtG10ZD
