development:
  facebook:
    report_url: https://www.facebook.com/help/contact/1449082462070065
    tokens:
      - EAAO0ZCIHKn24BAI8FriRBLaIHCDElXAR2rbM5PRwJ179h2YZADDwvSQo6QI8cBu27Yqc0iIdKXWAAuiy5ru6DbwPUXmp4xiXPgtATqqr8kuMzh1ZAiZCbnZCuPL0EeFXqi2QIwjNPvL0SaW9YzZCSKPecS0yWjB34ZD # alessandro

production:
  facebook:
    report_url: https://www.facebook.com/help/contact/1449082462070065
    tokens:
      - EAAO0ZCIHKn24BAI8FriRBLaIHCDElXAR2rbM5PRwJ179h2YZADDwvSQo6QI8cBu27Yqc0iIdKXWAAuiy5ru6DbwPUXmp4xiXPgtATqqr8kuMzh1ZAiZCbnZCuPL0EeFXqi2QIwjNPvL0SaW9YzZCSKPecS0yWjB34ZD # alessandro

demo:
  facebook:
    report_url: https://www.facebook.com/help/contact/1449082462070065
    tokens:
      - EAAO0ZCIHKn24BAI8FriRBLaIHCDElXAR2rbM5PRwJ179h2YZADDwvSQo6QI8cBu27Yqc0iIdKXWAAuiy5ru6DbwPUXmp4xiXPgtATqqr8kuMzh1ZAiZCbnZCuPL0EeFXqi2QIwjNPvL0SaW9YzZCSKPecS0yWjB34ZD # alessandro

test:
  facebook:
    report_url: https://www.facebook.com/help/contact/1449082462070065
    tokens:
      - EAAIUKbXn8xsBAPsYb2xKl4fcrpDnJKQZCrZB2EuLjHyg4GrXrlqnd1xHROqV3DFFbPRuzILTEwtoXLr5fo8PTxvvyN68uPUpbvCwnoIPrdJLmmKkuJXd2dMGekT8THoc2eZBuftIVXaLTN656NYzpxOu9FtG10ZD
