development:
  facebook:
    report_url: https://www.facebook.com/help/contact/1449082462070065
    tokens:
      - EAAIUKbXn8xsBABqlU1Lb0d3c0HcdL1Wyo3TJanKYvXx7pdkzNhvy3wMbmvvzjDgjn0rP6Pbf89XZACO0hURPEk7alZBz9JfJFDnQprajHLUnUKepSAlMNmrLg8B43tGtzjWLbae4CYPA2ZAb3l7kZAqBVNON2wsZD

production:
  facebook:
    report_url: https://www.facebook.com/help/contact/1449082462070065
    tokens:
      - EAAIUKbXn8xsBABqlU1Lb0d3c0HcdL1Wyo3TJanKYvXx7pdkzNhvy3wMbmvvzjDgjn0rP6Pbf89XZACO0hURPEk7alZBz9JfJFDnQprajHLUnUKepSAlMNmrLg8B43tGtzjWLbae4CYPA2ZAb3l7kZAqBVNON2wsZD

demo:
  facebook:
    report_url: https://www.facebook.com/help/contact/1449082462070065
    tokens:
      - EAAIUKbXn8xsBABqlU1Lb0d3c0HcdL1Wyo3TJanKYvXx7pdkzNhvy3wMbmvvzjDgjn0rP6Pbf89XZACO0hURPEk7alZBz9JfJFDnQprajHLUnUKepSAlMNmrLg8B43tGtzjWLbae4CYPA2ZAb3l7kZAqBVNON2wsZD

test:
  facebook:
    report_url: https://www.facebook.com/help/contact/1449082462070065
    tokens:
      - EAAIUKbXn8xsBAPsYb2xKl4fcrpDnJKQZCrZB2EuLjHyg4GrXrlqnd1xHROqV3DFFbPRuzILTEwtoXLr5fo8PTxvvyN68uPUpbvCwnoIPrdJLmmKkuJXd2dMGekT8THoc2eZBuftIVXaLTN656NYzpxOu9FtG10ZD
