development:
  facebook:
    report_url: https://www.facebook.com/help/contact/1449082462070065
    tokens:
      - PUT_A_REAL_TOKEN_HERE

production:
  facebook:
    report_url: https://www.facebook.com/help/contact/1449082462070065
    tokens:
      - EAAO0ZCIHKn24BAGeYHZA9kTmCD7lTu00hK1gPUkYyEnPlwZAm6ChXOj4XXKboKOpZCxIy319NInZCTHrhXtZALXdAc17kPglt8UQKmSSe9d4TAx2sJfcV86uxwpoYRVP5n9yea8k1ixt0iZBCb1RxcvRJXew635il0ZD # syed
      - EAAO0ZCIHKn24BAK2Hvye9nUXZC5iDLeyjhfvm8bqL5RXFqTwrJfFt63lmzZCD0VhQ0saGju2dtRwU2l6YZBYx7zI9SVSNoubNedQQ7Y9Rl2TizUBpHanWSpZBER0yxFNfhIwWOthUmAL4PnZBsIRF9Q57nsvV2ZCtE0GDQSjmaPgQZDZD # Arthur 
staging:
  facebook:
    report_url: https://www.facebook.com/help/contact/1449082462070065
    tokens:
      - EAAC2MKnLHGMBAHtqfRwGWsMMcDyaTTbQXV5SROskNe5F8Vhjr2G0CkwVVYHQVOf3fZBQC7TkcVX3PyPOhpSh5zP30TaxSZCIScxpyLUP4hTypZAAfe4mL2YQsfH6H9TTj95mPe9YgpZCvZCUBtNSA # Syed @ SanDev

test:
  facebook:
    report_url: https://www.facebook.com/help/contact/1449082462070065
    tokens:
      - EAAIUKbXn8xsBAPsYb2xKl4fcrpDnJKQZCrZB2EuLjHyg4GrXrlqnd1xHROqV3DFFbPRuzILTEwtoXLr5fo8PTxvvyN68uPUpbvCwnoIPrdJLmmKkuJXd2dMGekT8THoc2eZBuftIVXaLTN656NYzpxOu9FtG10ZD # test token, do not change
