default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: counterfind_oommaa_development

test:
  <<: *default
  database: counterfind_oommaa_test
