default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: counterfind_development

test:
  <<: *default
  database: counterfind_test

production:
  <<: *default
  database: counterfind_production
  username: counterfind
  password: rAIkCKD2dMatvz3SGiM
  pool: 15

staging:
  <<: *default
  database: counterfind_demo
  username: counterfind
  password: s897JHgJg87y6rtHFG
  pool: 15
